import type { CoordinationApplication } from "../../application/coordination-application.ts";

export type BrowserCoordinationCapabilities = Pick<CoordinationApplication,
  | "queryNotificationPolicy"
  | "queryProcessCostStatistics"
  | "updateNotificationPolicy"
  | "queryNotificationOccurrences"
  | "queryUserBoard"
  | "resumeAutomation"
  | "resumeWithCurrentProcess"
  | "pauseAutomation"
  | "createTask"
  | "queryArchivedTaskOverviews"
  | "archiveCompletedTasks"
  | "dismissStaleActivation"
  | "dismissActivation"
  | "queryAttemptTranscript"
  | "queryAgentConversation"
  | "continueAgentConversation"
  | "createConversationUpload"
  | "removeConversationUpload"
  | "readConversationAttachment"
  | "retireAgentConversation"
  | "archiveTask"
  | "unarchiveTask"
  | "queryTaskInspectionForUser"
  | "queryTaskWorkspaceGitState"
  | "queryUserTaskDetail"
  | "interruptTask"
  | "continueInterruptedTask"
  | "editTask"
  | "moveTask"
  | "createChildTask"
  | "createTaskRelationship"
  | "removeTaskRelationship"
  | "addTaskComment"
  | "markUserMentionAddressed"
  | "continuePermissionBlockedActivation"
  | "retryFailedActivation"
  | "dismissFailedActivation"
>;
